version: '3'

services:
  web:
    build: .
    command:  gunicorn women_in_stem.wsgi:application --bind 0.0.0.0:8000 --workers 2
    volumes:
      - .:/code
    ports:
      - "8000:8000"


  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - db-data:/var/lib/postgresql/data
    # ports:
    #   - 5432:5432
  
volumes:
  db-data: